import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Digital Thunder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/styles/globals.css" as="style" />
      </head>
      <body>
        <script>0</script>
        <ConfigProvider
          theme={{
            "token": {
              "colorPrimary": "#2d82fa",
              "colorInfo": "#32445c",
              "colorBgBase": "#FFFFF",
              "colorLink": "#152e50",
              "colorTextBase": "#ffffff"
            }
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
